replicaCount: 1
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-calibrate-app
  pullPolicy: Always
  tag: stage-e1a37dea-1669728890
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
service:
  type: NodePort
  protocol: TCP
  port: 80
  targetPort: 80
  nodePort: 31106
resources:
  limits:
    cpu: 50m
    memory: 80Mi
  requests:
    cpu: 5m
    memory: 20Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
app:
  name: airqo-stage-calibrate-app
  label: sta-calibrate-app
  namespace: staging
  configmap: env-calibrate-staging
